import { NFTModule } from "@/modules/nft";

export default function NFT() {
  return (
    <main className="flex-1">
      <div className="container pt-8 pb-20">
        <section className="mx-auto flex max-w-[980px] flex-col items-center gap-3 py-8">
          <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl text-center">
            Heurist Imaginaries Airdrop
          </h1>
          <h3 className="scroll-m-20 text-2xl font-semibold tracking-tight text-center">
            A gift for early supporters of Heurist.
          </h3>
          <p className="text-lg text-muted-foreground text-center">
            Imaginaries are a collection of 500 AI-generated NFTs generated by
            community-made Stable Diffusion models.
          </p>
          <NFTModule />
        </section>
      </div>
    </main>
  );
}
